<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-05-27 
 */

namespace Net\Bazzline\Component\ApiDocumentBuilder\Process;

use Net\Bazzline\Component\ProcessPipe\ExecutableInterface;
use Net\Bazzline\Component\ProcessPipe\InvalidArgumentException;
use Net\Bazzline\Component\ProcessPipe\Pipe;

class CreateNewProjectInTheCache extends Pipe
{
    /**
     * @param ExecutableInterface $process - or more
     * @param ExecutableInterface $_ [optional]
     * @throws InvalidArgumentException
     */
    public function __construct(ExecutableInterface $process = null, $_ = null)
    {
        parent::__construct($process, $_); // TODO: Change the autogenerated stub

        /*
        $create = new Create();
        $create($pathToProjectCache);
        chdir($pathToProjectCache);
        $git->create($project['url'], '.');
        */
        //$this->pipe()
    }
}