<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-05-27 
 */

namespace Net\Bazzline\Component\ApiDocumentBuilder\Requirement;

use Net\Bazzline\Component\Requirement\Requirement;

class CachedProjectHasChanges extends Requirement
{
    public function isMet()
    {
        //git update return is not 'Already up-to-date.'
        // or
        //git tag -l returns different tags
        return parent::isMet(); // TODO: Change the autogenerated stub
    }
}